"""compliment added.

Revision ID: 03bcc7ea94be
Revises: 75634cd49134
Create Date: 2025-07-24 16:15:22.127799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bcc7ea94be'
down_revision: Union[str, Sequence[str], None] = '75634cd49134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliments_id'), 'compliments', ['id'], unique=False)
    op.create_table('user_compliments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('compliment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compliment_id'], ['compliments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_compliments_id'), 'user_compliments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_compliments_id'), table_name='user_compliments')
    op.drop_table('user_compliments')
    op.drop_index(op.f('ix_compliments_id'), table_name='compliments')
    op.drop_table('compliments')
    # ### end Alembic commands ###
